version: "3"

services:
  redis:
    image: redis:alpine
    container_name: client
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
  app:
    depends_on:
      - redis
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
